# Using Node.js version 20 based on Alpine for a lightweight image
FROM node:20-alpine

# Create and change to the app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 443

# Run the app
CMD ["node", "index.js"]
