version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    container_name: dowell-proctoring-zookeeper
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    container_name: dowell-proctoring-kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  dowell-proctoring-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dowell-proctoring-backend
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    command: ["npm", "run", "dev"]
    depends_on:
      - kafka

  dowell-proctoring-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dowell-proctoring-frontend
    restart: always
    ports:
      - "4173:4173"
    expose:
      - "4173"
    command: ["npm", "run", "dev"]
    
  dowell-proctoring-peerjs:
    image: peerjs/peerjs-server
    container_name: dowell-proctoring-peerjs
    ports:
      - "9000:9000"
    environment:
      - PEERJS_PORT=9000
      - PEERJS_KEY=peerjs
      - PEERJS_PATH=/myapp

