FROM node:20-alpine AS build

# Install system dependencies
RUN apk add --no-cache \
    build-base \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    giflib-dev \
    librsvg-dev \
    pixman-dev \
    freetype-dev

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/backend/node_modules && chown -R node:node /usr/src/backend

# Switch to the root user
USER root

# Set the working directory in the container
WORKDIR /usr/src/backend

# Copy the package.json and package-lock.json
COPY package*.json ./

#Clear npm cache
RUN npm cache clean --force

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Command to run your app
CMD ["npm", "run", "dev"]
